### PR TITLE
Fixed Change icons to svg

### PR DESCRIPTION
**Pull request by alxlark**
Fixed issue #5 
Add svg icons in css

**INFO** folder source contain icons in svg and png. It can be deleted

It's how icons looks on zoom 300% in chrome
chrome_300percent

### CODE REVIEW

**Review by josephfusco — COMMENTED** [review]
This does not work on Microsoft Edge

**Comment by alxlark** [comment]
Please provide more infomation about issue?

**Comment by Fredrik-Oberg** [comment]
@alxlark I can confirm that the icons do not show In MS Edge.
It's due to that we need to URL encode them.
[reference](https://css-tricks.com/probably-dont-base64-svg/#article-header-id-1)

Edge version.

> Microsoft Edge 38.14393.0.0
> Microsoft EdgeHTML 14.14393

**Comment by alxlark** [comment]
@Fredrik-Oberg solution with encoded icons fix problem in Edge?

**Comment by Fredrik-Oberg** [comment]
@alxlark Works great!
closes issue #17

**Pull request merged**
